# jobs
role_keywords = {
    'data engineer': 'data engineering big data spark etl pipelines airflow databricks',
    'full stack developer': 'fullstack web development javascript react node angular backend frontend',
    'qa tester': 'software testing automation selenium qa pytest junit cucumber',
    'devops engineer': 'devops docker kubernetes ci cd terraform ansible linux cloud',
    'ai': 'machine learning deep learning artificial intelligence nlp neural networks',
    'product owner': 'agile scrum product owner backlog user stories roadmap product management',
    'scrum master': 'scrum master agile ceremonies kanban sprint facilitation retrospectives',
    'software architect': 'software architecture system design microservices scalability distributed systems',
    'mobile developer': 'android ios flutter react native mobile development swift kotlin',
    'data analyst': 'data analysis excel tableau powerbi statistics visualization business intelligence',
    'security engineer': 'cybersecurity ethical hacking penetration testing security network encryption',
    'cloud engineer': 'aws azure cloud computing architecture infrastructure cloud services',
    'frontend developer': 'html css javascript react angular vue frontend ui ux',
    'backend developer': 'java python node.js api backend databases spring django flask',
    'business analyst': 'business analysis requirements gathering stakeholders process modeling uml',
    'automation engineer': 'automation testing selenium webdriver test automation framework cucumber bdd tdd',
    'automation .net': '.net test automation c# selenium specflow nunit xunit restsharp postman api testing',
    'sdet': 'software development engineer in test c# java automation api selenium unit testing integration testing',
    'qa automation': 'qa automation engineer selenium testcomplete postman testng bdd rest api',
    'performance tester': 'performance testing loadrunner jmeter stress testing performance monitoring',
    'automation - java': 'java selenium testng maven cucumber rest assured api automation junit bdd',
    'automation - javascript': 'javascript automation testing playwright cypress mocha chai webdriverio',
    'automation - python': 'python selenium pytest unittest automation framework api testing requests bdd',
    'performance testing': 'performance testing jmeter loadrunner gatling stress testing scalability tuning',
    'security testing': 'security testing penetration ethical hacking vulnerability scanner owasp burp suite',
    'ai': 'artificial intelligence ai machine learning deep learning nlp neural networks tensorflow pytorch',
    'automation - typescript': 'typescript test automation playwright cypress end-to-end testing tdd bdd'
}